# Chromatic action from https://www.chromatic.com/docs/github-actions
# Using this github action from https://github.com/lightspeedretail/actions-label-prs

name: "chromatic"

on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  push:
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            packages:
              - 'storybook/**'

  visual-testing:
    needs: [paths-filter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: $CHROMATIC_PROJECT_TOKEN
          storybookBuildDir: "./.storybook/public"
          onlyChanged: "!(main)"
          autoAcceptChanges: main
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          
